# Generated by Django 4.0.5 on 2022-06-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('slots', models.CharField(max_length=200, null=True, verbose_name='Slots')),
                ('status', models.CharField(max_length=200, null=True, verbose_name='Status')),
            ],
        ),
    ]
