# Generated by Django 4.0.5 on 2022-06-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='contest.player'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slots',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=200, null=True, verbose_name='Slots'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING')], max_length=200, null=True, verbose_name='Status'),
        ),
    ]
