# Generated by Django 4.0.5 on 2022-06-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_tournament_player_alter_tournament_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('ENDED', 'ENDED')], max_length=200, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to='contest.competitors')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.tournament')),
            ],
        ),
    ]
