# Generated by Django 4.0.5 on 2022-06-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_alter_competitors_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitors',
        ),
    ]
