# Generated by Django 4.0.5 on 2022-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='phase',
            field=models.CharField(choices=[('STARTING LADDER', 'STARTING LADDER'), ('SEMIFINAL', 'SEMIFINAL'), ('FINAL', 'FINAL')], default='STARTING LADDER', max_length=200, verbose_name='Faza'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slots',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('8', '8')], max_length=200, null=True, verbose_name='Slots'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('ENDED', 'ENDED')], default='PENDING', max_length=200, verbose_name='Status'),
        ),
    ]
