# Generated by Django 4.0.5 on 2022-06-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_tournament_phase_alter_tournament_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Player 1 Win', 'Player 1 Win'), ('Player 2 Win', 'Player 2 Win'), ('In Progres', 'In Progres')], default='In Progres', max_length=200)),
                ('red_player', models.CharField(max_length=200, null=True)),
                ('blue_player', models.CharField(max_length=200, null=True)),
                ('phase', models.CharField(choices=[('STARTING LADDER', 'STARTING LADDER'), ('SEMIFINAL', 'SEMIFINAL'), ('FINAL', 'FINAL')], max_length=200, null=True, verbose_name='Faza')),
                ('partipant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.participants')),
            ],
        ),
    ]
