# Generated by Django 4.0.5 on 2022-06-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
