# Generated by Django 4.0.5 on 2022-06-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Zawodnik A wygrywa', 'Zawodnik A wygrywa'), ('Zawodnik B wygrywa', 'Zawodnik B wygrywa'), ('W trakcie', 'W trakcie')], default='W trakcie', max_length=200)),
                ('a_player', models.CharField(max_length=200, null=True)),
                ('b_player', models.CharField(max_length=200, null=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.tournament')),
            ],
        ),
    ]
