# Generated by Django 4.0.5 on 2022-06-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='phase',
        ),
    ]
