# Generated by Django 4.0.5 on 2022-06-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_alter_participants_player_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.player'),
        ),
    ]
